### PR TITLE
End of CodeElements grammar refactoring

### PR DESCRIPTION
**Pull request by laurentprudhon**
End of grammar refactoring for the following code elements : StringStatement, SubtractStatement, UnstringStatement, WriteStatement, XmlGenerateStatement, XmlParseStatement

### CODE REVIEW

**Comment by laurentprudhon** [comment]
This is a work in progress : I will add a comment here when all commits for this pull request are ready

**Comment by laurentprudhon** [comment]
Support for NULL/NULLS figurative constant in STOP statement added to this pull request via commit d8254e51

**Comment by laurentprudhon** [comment]
This commit could now be merged

**Comment by wiztigers** [comment]
Merged!
Thanks a lot, @laurentprudhon ⊙ω⊙

**Pull request merged**
