### PR TITLE
V1.5 to Master

### PR DESCRIPTION
**Pull request by mayanje**
### V1.5
**This release `1.5` mainly implements the construction of Control Flow Graph (CFG) for both Cobol and TypeCobol programs, and the support of Data Flow Analysis (DFA) for Cobol programs only.**

This version also provide support for a new quality step and external code analyzer loading (DLL).

A lot of bug have been fixed.

_https://en.wikipedia.org/wiki/Control-flow_graph_
_https://en.wikipedia.org/wiki/Data-flow_analysis_

## What's New ##

# Semantic Domain (#1262, #1264)
- New Semantic Domain Objects and Symbol table for better Symbols and Types representation (#1262, #1721, #1278)
- Store Section and Paragraph in the new Symbol table (#1394)
- Integrate SemanticDomain (#1721, #1722)
- Add Listener/Dispatcher interfaces for node creation/parsing (#1597).

# Control Flow Graph (#1260, #1396)
- Implement the data structure of a CFG graph (#1265)
- Integrate all TypeCobol control flow instructions (#1266).
- Build CFG graph for a TypeCobol program (#1267)
- Generate .dot file for a CFG program (#1268)
- Cobol specificities
    - Handle Program CFG without PROCEDURE-DIVISION (#1502)
    - Ignore EXEC-SQL Statement Out of a PROCEDURE DIVISION (#1501)
- Tests CFG .dot graph and visualiation (#1269)

# Data Flow Analysis (#1260, #627, #1720, #1750)
- Increase the CFG graph with data structures for DFA (#1270)
- Identify Cobol Instruction that target DFA (#1271)
- Apply DFA algorithms (#1272).
- Generate the .dot file of a DFG (#1273)
- Test DFG .dot graphs and visualization (#1274)
- Diagnostics
    - Dataflow diagnostics and TypeCobol diagnostics unification (#1285)
- Lite DFA Integration for Cobol only (#1750)
- Add DataDefinition nodes as CFG instructions in the START block of a DFG (#1750)

# CFG/DFA in practice
- Quality rule: Identify module called by a zcallpgm (#1275)

# Cobol Parser improvments
- Better handling of scan state dependent tokens(#428)
- Forbid SYNC clause with Strict Type (#960, #1729)
- Handle SYNC LEFT and RIGHT (#1200)

# Semantic Domain towards Analyzers for Quality rules
- cfg semantic domain lite introduce analyzers (#1739) 

# Performance, tests and Stats (issues and improvements)
This version decrease performance.
Full parsing of a source can be 5% to 20% slower than 1.4.3
CFG/DFA activation doesn't impact performance so much (0% to 15%)

Incremental mode is 42% to 112% slower.
CFG/DFA activation in incremental doesn't impact performance so much (0% to 15%)

- Update performance tests to take into account CFG/DFA construction (#1863, #1864, #1851)
- Cobol Parser
    - Use hand-code algorithm instead of regular expression, to parse PICTURE strings (#1357)
- Update GlobalStorage test with new Semantic errors (#1133)

# TypeCobol Options
- Add a new option to specify the path of the log file TypeCobol.CLI.Log (#1513)

# Towards Quality Rules
- Add Rules and Violations concepts to the parser (#1837)
- Support external analyzers (#1825)
- Introduce new QualityCheck compilation step (#1816)
- Add .xmldiag format for error output in CLI (#1845)
- Remove IASTAnalyzer, use QualityAnalyzer concept instead (#1869)

# Minor and other changes
- Change Internal class visibility and scope (#1766)
- Internal Code Refactoring
    - Remove unused dependencies: (Razor, Moq...) (#1679, #1682)
    - Disable CodeAnalysis for Debug-like configurations (#1800)
    - Align all csproj configuration and properties to use the common ones (#1627)
	- Upgrade NLog to v4.7.2 (#1772)

# Bug Fix
- Language Server
    - LSP Signature Help Request raise exception (#1811)
	- Send notification for all logged exceptions (#1622)
- Cobol EI Parser	
    - Exception on sources with broken format (#1852)
	- Tokens replaced need the MultilineScanState to determine their type (#428) 
	- Complete the missing copies list with all levels of inclusion (#1808)
	- Wrong inital values for data using continuation lines (#1791)
	- Bug in tag/placeholder replacing (#1785)
	- Continuation line parsing breaks when mixed with comment lines (#1777)
	- Copy replacing for a level(#1753)
	- Strict parsing of *CBL directives(#1748)
	- Invalid cast in CrossCheck (#1746)
	- Empty IF ELSE should be allowed in grammar but checked in CrossChecker (#1676)
	- Bug in DataDefinition with continuation lines (#1671)
	- DataRenames node are generated as children of previous node (#1192)
	- Unterminated literals doesn't generate an error (#1160)
	- TALLY is changed to ALL in error message (#1120)
	- Replaced Token doesn't work inside DataDivision (#599)
	- Arguments of standard call are not controlled (#532)
	- Continuation line (#457)
	- Tokens replaced need the MultilineScanState to determine their type (#428)
	- EXEC SQL INCLUDE on multiple lines doesn't works (#321)
	- Check duplicate paragraph names with semantic data owner (#1710)
	- Replace all placeholders in partial word replace operations (#1780)
	- Fix numeric literal detection in scanner after THROUGH/THRU (#1778)
	- Allow "VALUE ARE"/"VALUES IS" in data condition value clauses (#1782)
	- Allow modification on input indices in procedures (#1789)
	- handle copy replacing with 4colon ol (#1752)

### CODE REVIEW

**Comment by smedilol** [comment]
Can you add the whole changelog of v1.5 in this PR ?
This PR also target to validate this changelog.

**Review by smedilol — CHANGES_REQUESTED** [review]
Can you add the whole changelog of v1.5 in this PR ?
This PR also target to validate this changelog.

**Comment by mayanje** [comment]
Sure I am working on this aspect, I will inform you when it will be ready

**Comment by mayanje** [comment]
In the change log only issues of Milestone v1.5 have been taken in account.

**Comment by mayanje** [comment]
Je vais aussi intégrer les issues closed des milestones CobolEditorEI et Quality Rule

**Comment by smedilol** [comment]
Everything about new SymbolTable can be removed as it was abandonned (like **Global-storage visibility integration in the new Symbol table (#1391, #805)**).
You can also removed references to PR. We only need references to issues.

**Comment by fm-117** [comment]
Updated changelog:
- fix typo
- move quality analyzer issues references to proper section (instead of bug fixes)

**Comment by mayanje** [comment]
Change Log shall be ok now

**Review by fm-117 — APPROVED** [review]
- removed codegen from changelog as simplified codegen has not been merged, it was only a test
- fixed issue reference for QualityCheck
- moved #1800 reference to proper section
- removed #216 as it has been cancelled rather than closed

You can check my edits of the changelog.

**Comment by smedilol** [comment]
I've made a small update:
- I removed PR references
- I removed one line about new Symbol table

You can check my edits of the changelog.

**Comment by smedilol** [comment]
Other update:
- regroup bug fix by category
- remove some duplicate entries
- rename `TypeCobol Options` to `Command Line Interface`

You can check my edits of the changelog.

@mayanje Can you post figures about performance of v1.5 VS v1.4.3 ? Also with differents options without CFG/DFA, with CFG standard, CFG extented, DFA.

**Comment by mayanje** [comment]
@smedilol what do you mean by posting figures?
There are four différents tests v1.4.3,  v1.5 NoCfg , v1.5CfgStandard and v1.5DFAExtended, results are cvs files.

**Review by rooksdo — APPROVED** [review]

**Comment by smedilol** [comment]
Another update:
Add more info about performance.
Add 2 info in the summary.

**Review by smedilol — APPROVED** [review]

**Pull request merged**
