### PR TITLE
v1.4.3 release

### PR DESCRIPTION
**Pull request by rooksdo**
# New
This is a fix release with no new features.

# Fixed
- Explicit error message for copy declaration with 01 level #1637
- TC-INITIALIZATIONS generated before debugging declaratives #1713
- Allow for pointer address change on procedure input parameter #1625
- Wrong index hash generation for global storage variable #1718
- Function overload fails with nested type in dependancy file #1747

### CODE REVIEW

**Review by smedilol — CHANGES_REQUESTED** [review]
WI #1762 is missing in the description

**Review by smedilol — CHANGES_REQUESTED** [review]
Milestone 1.4.3 https://github.com/TypeCobolTeam/TypeCobol/milestone/80 still contains a lot of elements.
Can you dispatch them in the good milestone ?

**Comment by rooksdo** [comment]
> 
> 
> WI #1762 is missing in the description
The list of fixed bugs details the issues addressed with this release. So issue #1762 is actually the 2nd bullet point in #1718

**Comment by rooksdo** [comment]
> 
> 
> Milestone 1.4.3 https://github.com/TypeCobolTeam/TypeCobol/milestone/80 still contains a lot of elements.
> Can you dispatch them in the good milestone ?

Ok, issues/pr have been dispatched between v1.5.1 and CobolEditor milestones, and one more in intern & technical issues.

**Review by smedilol — APPROVED** [review]

**Pull request merged**
