### PR TITLE
WI #1753 Unify TokenType promote IntegerLiteral in favor of NumericLevel

### LINKED ISSUE #1753: Copy replacing for a level
**Describe the bug**
Copy replacing that want to change a level number doesn't works.
It certainly related to #428 (check the proposed solution)
When this issue is resolved, also if it resolves #599.

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZF0OSM.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 MyGroup.
           COPY YXXXENT REPLACING  ==:XXXENT:==  BY ==XXXENT==
                                   ==01 :XXXENT:== BY ==02 XXXENT==.
      
       END PROGRAM DVZF0OSM.
```

With YXXXENT :
```cobol
       01 :XXXENT:.
          05 :XXXENT:-G1.
                20 :XXXENT:-Var1        PIC X(01).
```
Our parser report the error `Syntax error : A group item cannot be empty.` on variable `MyGroup`
The replacing `==01 :XXXENT:== BY ==02 XXXENT==` doesn't works

**Expected behavior**
No error.
Variable `01 :XXXENT:` is replaced by `02 XXXENT`.

### PR DESCRIPTION
**Pull request by mayanje**
Fixes #1753

### CODE REVIEW

**Review by rooksdo — APPROVED** [review]

**Review by smedilol — COMMENTED** [review]
The solution works but is specific to token LevelNumber/IntegerValue.
Can you try to scan tokens after replacing.
Like what is done for PartialCobolWord in ReplaceTokensLinesIterator, method CreateReplacedTokens
LIne :
 Token generatedToken = Scanner.Scanner.ScanIsolatedTokenInDefaultContext(tokenText, out error);

**Review by fm-117 — CHANGES_REQUESTED** [review]

**Comment by mayanje** [comment]
@smedilol yes the solution work for the context dependent token LevelNumber. Are there other tokens that are context dependent, and that can generate such issue?

**Comment by smedilol** [comment]
@mayanje 
> @smedilol yes the solution work for the context dependent token LevelNumber. Are there other tokens that are context dependent, and that can generate such issue?
Yes, see #599

**Comment by mayanje** [comment]
@smedilol, Ok really interresting #599 :-|

**Comment by mayanje** [comment]
@smedilol I created a PR for #599 https://github.com/TypeCobolTeam/TypeCobol/pull/1797
The suggested fix does not resolve this issue, so the fix in this PR is suitable for this only one context.

**Comment by smedilol** [comment]
Ok, but the solution in #1797 is only for PartialCobolWord.
My remarks about #428 was to find a common way to resolve both #599 and #1753.

**Comment by mayanje** [comment]
Handle by PR #1798

**Pull request closed without merging**
