### PR TITLE
Refactoring of CodeElements grammar to embrace the ambiguity of symbol types at this stage

### PR DESCRIPTION
**Pull request by laurentprudhon**
Huge refactoring effort (+15 000 lines / - 11 000 lines) to manage properly the fact that : 
- symbol types are most often unknown at the first parsing stage (CodeElements)
- and can be resolved only later at the second parsing stage (ProgramClass)

The following grammar files have been largely rewritten : CobolWords.g4, CobolExpressions.g4, CobolCodeElements.g4.

The code element classes have been significantly updated in : CodeElements/Expressions, CodeElements/*.

The following parser helper classes have been completely rewritten : CobolWordsBuilder, CobolExpressionsBuilder, CobolCodeElementsBuilder, CobolStatementsBuilder.

All data analysis properties have been moved from CodeElements/DataDescriptionEntry to CodeModel/DataDefinitionNode.

All the other classes still need to be adjusted to these changes.
Most importantly, we need to update the symbol resolution code to execute it later, during the second parsing stage, taking into account the ambiguity in symbol types detected during the first parsing stage.

The master branch of the TypeCobolTeam has been regularly merged in this refactoring, but right now :
- the refactoring branch does not compile, it is a work in progress
- no test has been executed and you can expect a significant effort to get to a point where all unit tests are running again

### CODE REVIEW

**Comment by wiztigers** [comment]
The majority of this PR is now merged in branch `merge#249`.
However, there's still a lot of work necessary _just_ to make this compile.

**Comment by wiztigers** [comment]
Project now compiles without errors (at least!).
However, all important tests fail, because we have to uncomment and rework all that has the `TODO#249` tag. This will consist at least of two main tasks:
* rewrite _all_ ProgramClass and friends classes, mainly SymbolTable, because with this PR we lose all previous name qualification data structures
* rethink and rewrite all `NodeCheckers` (and some `CodeElementCheckers`, too)

**Comment by wiztigers** [comment]
As of 5c8bc81740b6045e67ca682eafb5b4a804514d14
* everything compiles,
* all unit tests pass, and
* there is no error when parsing our production sample (excepted paragraph names that look like arithmetic operations, but `master` already has them and it is a known limitation of our parser)

I'll now merge the branches in git like described in #303

**Comment by wiztigers** [comment]
Done ae5f25e007241bb1809c3a50a95705825bb7c5cc.
whew !! ヾ(＠⌒ー⌒＠)ノ

**Comment by smedilol** [comment]
Yeeeeeeaaaahhhhhh

**Comment by wiztigers** [comment]
^^

C’est pas encore « tout à fait » terminé, je suis en train d’écrire dans #303 pour nos archives.
T’auras un dernier truc à faire.

**Pull request closed without merging**
